### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by cfpwastaken** [loumadev/EdupageAPI#1]
Is there some kind of documentation so I can know how this API works?

**Comment by loumadev** [comment]
This project is not ready yet. There are still missing some key features. The documentation will be added after those soon. (I have already done some research and scraping so it is only waiting for implementation.)
I will add detailed descriptions of all classes and methods as well as some examples in few days.

**Comment by loumadev** [comment]
Hello, so I've just added some simple examples and API documentation. It's not the best way to document an API, but it's enough for now.
In case of any questions feel free to open an issue.
