### ISSUE TITLE
Listening for the substitution notifications

### ISSUE THREAD

**Issue by atomicra1n** [loumadev/EdupageAPI#18]
Zdravím, doufám že nevadí že budu psát česky.
Chtěl jsem se zeptat zda by bylo možné díky EdupageAPI napsat do konzole vždy když se nahraje na web suplování pro mojí třídu, zkoušel jsem to ale nepodařilo se mi to. 

Je to možné?
Díky, 
Megami.

EDIT: _translated_

Greetings, I hope it doesn't matter that I will write in Czech.
I'd like to ask, if it is be possible, thanks to EdupageAPI, to print into the console when there's a new substitution uploaded to the web for my class, I've tried it myself, but it I failed.

Is it possible?
Thanks,
Megami.

**Comment by loumadev** [comment]
Hey,
it is better to always write in English, so other people can understand as well, but to your question:
Yes, this is possible. You can slightly modify the code in #4 and get the effect you are looking for.

The code might look like this:
```js
const {Edupage, TIMELINE_ITEM_TYPE} = require("edupage-api");

const edupage = new Edupage();
const MESSAGE_UPDATE_INTERVAL_MS = 10000;   //After this time the messages get refreshed (smaller value = smaller delay, but highier load)

(async () => {
	await edupage.login(USERNAME, PASSWORD);

	let oldTimeline = edupage.timeline;

	//Create an update interval
	setInterval(async () => {
		//Every `MESSAGE_UPDATE_INTERVAL_MS` milliseconds refresh all messages
		await edupage.refreshTimeline();

		const substitutions = edupage.timeline
			//Filter out old messages
			.filter(e => !oldTimeline.find(t => t.id == e.id))
			//Filter out all timeline items except substitution notifications
			.filter(e => e.type == TIMELINE_ITEM_TYPE.SUBSTITUTION);

		//Mark new messages as old so you can identify new ones on the next interval iteration
		oldTimeline = edupage.timeline;

		//If there are any new substitutions, run this statement (you can consider this as a callback function)
		if(substitutions.length) {
			//Your code here...
			console.log(substitutions);
		}
	}, MESSAGE_UPDATE_INTERVAL_MS);
})();

```

**Comment by atomicra1n** [comment]
@loumadev Hi, sorry and thank you, but I Have a question. Wont that log all substitutions? I really only need the ones for my class. Any ideas as to how I could achieve that?
Thanks.

**Comment by loumadev** [comment]
Hmm, now I can see where you are pointing. It actually will log all the messages, and there's unfortunately no available way to get substitution details in the current state of this project. Parsing substitution data is especially hard, since all rendering is done on the server side, and we get nearly plain text out of it. I've also found out, that the school administrator is probably able to change a style of the substitution page, so it would be even harder to include all possible cases.

**Comment by atomicra1n** [comment]
@loumadev Oh, so the concept of logging all substitutions for my class into a Discord channel is practically impossible at the moment?

**Comment by loumadev** [comment]
You could send the request for the substation page yourself and then just check if the page is containing the name of your class, and then you can determine if the substitution is for your class. But it is probably more complicated, so I guess you are right.

**Comment by ivanhrabcak** [comment]
This is possible with [edupage-api](https://github.com/ivanhrabcak/edupage-api), if you are willing to rewrite your discord bot in python of course.
