### ISSUE TITLE
SyntaxError: Unexpected token '.' at /node_modules/edupage-api/src/Edupage.js:191

### ISSUE THREAD

**Issue by waheed-isk** [loumadev/EdupageAPI#3]
Hi,
I'm trying to run the sample code in readme for getting timetable. The only thing I changed is the username and password arguments.
I get the following error.

/node_modules/edupage-api/src/Edupage.js:191
                iterate(_grades.data?.vsetkyUdalosti || {})

SyntaxError: Unexpected token '.'

Its the '.' after ` iterate(_grades.data?`
in front of `vsetkyUdalosti || {})`

**Comment by loumadev** [comment]
Hello,
this module is using the latest JavaScript features and one of them is [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) `?.`. This feature is available for Node.js v14.0.0 or above, so please make sure your installed version of Node.js supports this feature.

You can check your Node.js version using `node -v`.

Most likely you will need to update your Node.js.
