### ISSUE TITLE
Listening for a new items (messages) on the timeline

### ISSUE THREAD

**Issue by ghost** [loumadev/EdupageAPI#4]

**Comment by Mareceeek** [comment]
i want to fetch new messages from edupage and post them to console do you know how?

**Comment by loumadev** [comment]
Hello, what do you mean by fetching new messages from Edupage?

Do you mean it like:
 * having some kind of listener which listens for new messages and fires a callback as soon as a new message is received?
 * or like single check if there are any unseen messages on the timeline?
 * or is there something different on your mind?

Specify the request, please, so I can help you correctly.

**Comment by Mareceeek** [comment]
i mean this having some kind of listener which listens for new messages and
fires a callback as soon as a new message is received

ut 14. 9. 2021 o 22:45 Jaroslav Louma ***@***.***> napísal(a):

**Comment by loumadev** [comment]
For this purpose, you can use the following snippet:
```javascript
const {Edupage, TIMELINE_ITEM_TYPE} = require("edupage-api");

const edupage = new Edupage();
const MESSAGE_UPDATE_INTERVAL_MS = 10000;  //After this time the messages get refreshed (smaller value = smaller delay, but highier load)

(async () => {
    await edupage.login(USERNAME, PASSWORD);

    //Keep track of an old messages
    let oldTimeline = edupage.timeline;

    //Create an update interval
    setInterval(async () => {
        //Every `MESSAGE_UPDATE_INTERVAL_MS` milliseconds refresh all messages
        await edupage.refreshTimeline();

        const newMessages = edupage.timeline
            //Filter out old messages (required)
            .filter(e => !oldTimeline.find(t => t.id == e.id))
            //Filter out messages created by the current user (i.e. you are sending a message, but the message on the timeline apears anyway so callback fires) (optional)
            .filter(e => e.owner != edupage.user)
            //Filter out all timeline items except messages (those sent directly by the users) (optional)
            .filter(e => e.type == TIMELINE_ITEM_TYPE.MESSAGE);

        //Mark new messages as old so you can identify new ones on the next interval iteration
        oldTimeline = edupage.timeline;

        //If there are any new messages, run this statement (you can consider this as a callback function)
        if(newMessages.length) {
            //Your code here...
            console.log(newMessages);
        }
    }, MESSAGE_UPDATE_INTERVAL_MS);
})();
```

You could also wrap it into some `MessageListener` class for example to make it more flexible.

**Comment by Mareceeek** [comment]
it will tell me this error
[image: image.png]
this is my code
const {Edupage, TIMELINE_ITEM_TYPE} = require("edupage-api");

const edupage = new Edupage();
const MESSAGE_UPDATE_INTERVAL_MS = 10000;
//After this time the messages get refreshed (smaller value = smaller
delay, but highier load)

(async () => {
    await edupage.login(username, password);

    //Keep track of an old messages
    let oldTimeline = edupage.timeline;

    //Create an update interval
    setInterval(async () => {

//Every `MESSAGE_UPDATE_INTERVAL_MS` milliseconds refresh all messages
        await edupage.refreshTimeline();

        const newMessages = edupage.timeline
            //Filter out old messages (required)
            .filter(e => !oldTimeline.find(t => t.id == e.id))

//Filter out messages created by the current user (i.e. you are
sending a message, but the message on the timeline apears anyway so
callback fires) (optional)
            .filter(e => e.owner != edupage.user)

//Filter out all timeline items except messages (those sent directly
by the users) (optional)
            .filter(e => e.type == TIMELINE_ITEM_TYPE.MESSAGE);


//Mark new messages as old so you can identify new ones on the next
interval iteration
        oldTimeline = edupage.timeline;


//If there are any new messages, run this statement (you can consider
this as a callback function)
        if(newMessages.length) {
            //Your code here...
            console.log(newMessages);
            webhookClient.send({
                content: newMessages
            });
        }
    }, MESSAGE_UPDATE_INTERVAL_MS);
})();

pi 17. 9. 2021 o 0:24 Jaroslav Louma ***@***.***> napísal(a):

**Comment by Mareceeek** [comment]
it will tell me this error
[image: image.png]
this is my code
//Webhook
const { WebhookClient } = require('discord.js');
const webhookClient = new WebhookClient({ url: '
https://discord.com/api/webhooks/887062328741347388/AzAsNkOysc8veDUDm5lm4DyLN8WN3CIZfNLRie7brpSS9rw-KH5fq3iw3QIVjlbbzSjl
' });

const {Edupage, TIMELINE_ITEM_TYPE} = require("edupage-api");

const edupage = new Edupage();
const MESSAGE_UPDATE_INTERVAL_MS = 10000;
//After this time the messages get refreshed (smaller value = smaller
delay, but highier load)

(async () => {
    await edupage.login(username, password);

    //Keep track of an old messages
    let oldTimeline = edupage.timeline;

    //Create an update interval
    setInterval(async () => {

//Every `MESSAGE_UPDATE_INTERVAL_MS` milliseconds refresh all messages
        await edupage.refreshTimeline();

        const newMessages = edupage.timeline
            //Filter out old messages (required)
            .filter(e => !oldTimeline.find(t => t.id == e.id))

//Filter out messages created by the current user (i.e. you are
sending a message, but the message on the timeline apears anyway so
callback fires) (optional)
            .filter(e => e.owner != edupage.user)

//Filter out all timeline items except messages (those sent directly
by the users) (optional)
            .filter(e => e.type == TIMELINE_ITEM_TYPE.MESSAGE);


//Mark new messages as old so you can identify new ones on the next
interval iteration
        oldTimeline = edupage.timeline;


//If there are any new messages, run this statement (you can consider
this as a callback function)
        if(newMessages.length) {
            //Your code here...
            console.log(newMessages);
            webhookClient.send({
                content: newMessages
            });
        }
    }, MESSAGE_UPDATE_INTERVAL_MS);
})();

pi 17. 9. 2021 o 0:24 Jaroslav Louma ***@***.***> napísal(a):

**Comment by loumadev** [comment]
Could you please resend the image of the error or rather send it as text. I can't see the image, my github is little strange now. (Even code highlighting is not working. Probably because I'm kinda busy now and can't have access my PC so I'm using only my mobile phone.)

**Comment by Mareceeek** [comment]
okay this is the error
![image](https://user-images.githubusercontent.com/70047384/133770327-288b018a-871b-4278-a911-8c303b06a639.png)

and this is the code
//Webhook
const { WebhookClient } = require('discord.js');
const webhookClient = new WebhookClient({ url: 'https://discord.com/api/webhooks/887062328741347388/AzAsNkOysc8veDUDm5lm4DyLN8WN3CIZfNLRie7brpSS9rw-KH5fq3iw3QIVjlbbzSjl' });

const {Edupage, TIMELINE_ITEM_TYPE} = require("edupage-api");

const edupage = new Edupage();
const MESSAGE_UPDATE_INTERVAL_MS = 10000;  //After this time the messages get refreshed (smaller value = smaller delay, but highier load)

(async () => {
    await edupage.login(username, password);

    //Keep track of an old messages
    let oldTimeline = edupage.timeline;

    //Create an update interval
    setInterval(async () => {
        //Every `MESSAGE_UPDATE_INTERVAL_MS` milliseconds refresh all messages
        await edupage.refreshTimeline();

        const newMessages = edupage.timeline
            //Filter out old messages (required)
            .filter(e => !oldTimeline.find(t => t.id == e.id))
            //Filter out messages created by the current user (i.e. you are sending a message, but the message on the timeline apears anyway so callback fires) (optional)
            .filter(e => e.owner != edupage.user)
            //Filter out all timeline items except messages (those sent directly by the users) (optional)
            .filter(e => e.type == TIMELINE_ITEM_TYPE.MESSAGE);

        //Mark new messages as old so you can identify new ones on the next interval iteration
        oldTimeline = edupage.timeline;

        //If there are any new messages, run this statement (you can consider this as a callback function)
        if(newMessages.length) {
            //Your code here...
            console.log(newMessages);
            webhookClient.send({
                content: newMessages
            });
        }
    }, MESSAGE_UPDATE_INTERVAL_MS);
})();

**Comment by Mareceeek** [comment]
i want to send the new messages into discord webhook

**Comment by loumadev** [comment]
I have released a new version, so please update the current one by `npm update edupage-api`. It should help with crashing the program, but the bug itself isn't fixed.
You will probably get some warnings, so you may want to post these warnings as a new issue, so I could try to fix them.
It's really hard to debug such a messy, undocumented project with tons of variations, it's practically impossible since I don't have your data, which cause the issues.

**Comment by Mareceeek** [comment]
okay
