### ISSUE TITLE
failed to parse redirect url. 

### ISSUE THREAD

**Issue by maxschnee-dev** [loumadev/EdupageAPI#9]
hello. i am currently just trying to grab a timetable. but my school has got a custom subdomain [here](https://sbs-cm.edupage.org/).

and cant seem to find out to use "Edupage.Login". Thanks In Advance

**Comment by loumadev** [comment]
Hello,
as far I know, all the schools are using URLs with "custom" subdomains in the format of `<subdomain>.edupage.org`.
Does your school follow the above pattern after logging in?

Why are you not able to use `Edupage.login`? Does it log any errors? Could you please specify your issue closely?

We have already experienced an issue (#5) with a similar problem where the school subdomain contained a hyphen character and that broke things up. But it got fixed right after the discovery, so please make sure you are using the [latest version](https://github.com/loumadev/EdupageAPI/releases/tag/v0.7.12).

**Comment by loumadev** [comment]
@Rebble69 any update? Was the issue resolved with the latest release?

**Comment by Rebble69** [comment]
figured it out lol

**Comment by Rebble69** [comment]
> @Rebble69 any update? Was the issue resolved with the latest release?

sorry for the late reply. yes the newest realease fixed the problem 👍

**Comment by maxschnee-dev** [comment]
Sorry for the late reply.

error ⬇️

```
# Error thrown:
#  ParseError: Failed to parse redirect URL
#      at E:\!codingstuff\edupagetest\node_modules\edupage-api\src\User.js:222:38
#      at processTicksAndRejections (node:internal/process/task_queues:96:5)
#
# Summary:
#  Time: Sun Jan 09 2022 22:59:07 GMT+0700 (Indochina Time)
#  EdupageAPI version: v0.7.14
#  Node.js version: v16.13.0
#  Error log: E:\!codingstuff\edupagetest\node_modules\edupage-api\logs\fatal_error_2022-01-09T15-59-07Z.json
#
# If you would like to submit an issue, please visit:
#  > https://github.com/loumadev/EdupageAPI/issues
#  (Please, include this error message + error log)
```

**Comment by maxschnee-dev** [comment]
[this](https://github.com/ivanhrabcak/edupage-api) python lib has worked for me.

**Comment by cfpwastaken** [comment]
This issue has been fixed and it is working. This issue can be closed.

**Comment by maxschnee-dev** [comment]
awesome thanks!
